format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$golang\
$guix_shell\
$terraform\
$nix_shell\
$conda\
$aws\
$gcloud\
$azure\
$env_var\
$custom\
$sudo\
$cmd_duration\
$fill\
$python\
$kubernetes\
$line_break\
$jobs\
$status\
$os\
$container\
$shell\
$character\
"""  
# '$fill' moves following elements to the right and fills the space
# '$line_break' adds a line break
# '$character' displays the actual prompt character

[fill]
symbol = '─'  # not a hyphen but a box-drawing character
style =  '236'

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[package]
disabled = true

[directory]
truncate_to_repo = false

[python]
format = '[(${symbol}$virtualenv )]($style)'